/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controladores.ControleFuncionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Funcionario;
import objetos.FuncionarioPF;



/**
 *
 * @author User
 */
public class TelaControle extends javax.swing.JDialog {

    private TelaLogin telaLogin = new TelaLogin();
    private FuncionarioPF usuario;
    private ControleFuncionario controleFuncionario;
    
    public TelaControle(java.awt.Frame parent, boolean modal, FuncionarioPF funcionario) {
        super(parent, modal);
        initComponents();
         this.controleFuncionario = new ControleFuncionario(new ArrayList<> ());
         usuario = funcionario;
        jTextUsuario.setText(funcionario.getNome());
        jTextUsuario.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButtonPdv = new javax.swing.JButton();
        jButtonFunc = new javax.swing.JButton();
        jButtonProd = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonPdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPdv.setText("PDV");
        jButtonPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPdvActionPerformed(evt);
            }
        });

        jButtonFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFunc.setText("Funcionários");
        jButtonFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncActionPerformed(evt);
            }
        });

        jButtonProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProd.setText("Produtos");
        jButtonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdActionPerformed(evt);
            }
        });

        jButtonRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRelatorio.setText("Relatórios");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuário:");

        jTextUsuario.setText("jTextField1");

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonProd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSair)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addComponent(jButtonPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(628, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncActionPerformed
       
        if("Financeiro".equalsIgnoreCase(usuario.getFuncao()) || "Gerente".equalsIgnoreCase(usuario.getFuncao()) || "Dono".equalsIgnoreCase(usuario.getFuncao())){
            TelaFuncionario telaFuncionario = new TelaFuncionario(null,true, usuario);
            dispose();
            telaFuncionario.setVisible(true);
           
        }else{
            JOptionPane.showMessageDialog(null, "Você não tem acesso a essa funcionalidade!");
        }
        
    }//GEN-LAST:event_jButtonFuncActionPerformed

    private void jButtonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdActionPerformed
       
        if("Financeiro".equalsIgnoreCase(usuario.getFuncao()) || "Gerente".equalsIgnoreCase(usuario.getFuncao()) || "Dono".equalsIgnoreCase(usuario.getFuncao())){
            TelaProduto telaProduto = new TelaProduto(null,true, usuario);
            dispose();
            telaProduto.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Você não tem acesso a essa funcionalidade!");
        }
    }//GEN-LAST:event_jButtonProdActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
      
        if("Financeiro".equalsIgnoreCase(usuario.getFuncao()) || "Dono".equalsIgnoreCase(usuario.getFuncao())){
            TelaRelatorio telaRelatorio = new TelaRelatorio(null,true, usuario);
            dispose();
            telaRelatorio.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Você não tem acesso a essa funcionalidade!");
        }
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        usuario.setLogado(false);
        controleFuncionario.setLogInLogOut(usuario);
        dispose();
        telaLogin.setVisible(true);
        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPdvActionPerformed
       if("Dono".equalsIgnoreCase(usuario.getFuncao()) || "Caixa".equalsIgnoreCase(usuario.getFuncao()) || "Gerente".equalsIgnoreCase(usuario.getFuncao())){
            TelaPrincipal telaPrincipal = new TelaPrincipal(usuario);
            dispose();
            telaPrincipal.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Você não tem acesso a essa funcionalidade!");
        }
    }//GEN-LAST:event_jButtonPdvActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFunc;
    private javax.swing.JButton jButtonPdv;
    private javax.swing.JButton jButtonProd;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
