/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controladores.ControleProduto;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Produto;
import pdv.OpAuxiliar;

/**
 *
 * @author User
 */
public class TelaInserirAlterarProd extends javax.swing.JDialog {

    private ControleProduto controleProduto;
    private Produto produto;
    private OpAuxiliar opAuxiliar;
    private boolean confirmado;
    private int cod;
    
    public TelaInserirAlterarProd(java.awt.Frame parent, OpAuxiliar opAuxiliar, Produto produto) {
         super(parent, true);
        confirmado = false;
        this.opAuxiliar = opAuxiliar;
        this.produto = produto;
        initComponents();
        controleProduto = new ControleProduto(new ArrayList<>());
        
        if (opAuxiliar == opAuxiliar.ocAlterar
                || opAuxiliar == OpAuxiliar.ocConsultar) {
            jLabelTitulo.setText(null);
            jLabelTitulo.setText("Produto");
            jLabelCod.setText(Integer.toString(produto.getCodigo()));
            txtNome.setText(produto.getNome());
            txtPreco.setText(produto.getPreco().toPlainString());
            txtEstoque.setText(Float.toString(produto.getQtdEstoque()));
            txtQtdAbnt.setText(Float.toString(produto.getQtdUnidadeAbt()));
            if(produto.isVendaFraconada() == true){
                jComboBoxVF.removeAllItems();
                jComboBoxVF.insertItemAt("sim", 0);
                jComboBoxVF.insertItemAt("não", 1);
            }else{
                jComboBoxVF.removeAllItems();
                jComboBoxVF.insertItemAt("não", 0);
                jComboBoxVF.insertItemAt("sim", 1);
            }
            
            
        }else{
            jCod.setVisible(false);
            jLabelCod.setVisible(false);
        }
    }
    
    public boolean opConfirmada(){
        return confirmado;
    }
    
    public static boolean executar(java.awt.Frame parent, OpAuxiliar opAuxiliar, Produto produto){
        TelaInserirAlterarProd telaInserirAlterarProd = new TelaInserirAlterarProd(parent, opAuxiliar, produto);
        telaInserirAlterarProd.setLocationRelativeTo(null);
        telaInserirAlterarProd.setVisible(true);
        return telaInserirAlterarProd.opConfirmada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCod = new javax.swing.JLabel();
        jPreco = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonConcluir = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jEstoque = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jUnd = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBoxUnd = new javax.swing.JComboBox<>();
        txtQtdAbnt = new javax.swing.JTextField();
        jQtd = new javax.swing.JLabel();
        jUnd1 = new javax.swing.JLabel();
        jComboBoxVF = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCod.setText("Código do Produto:");

        jPreco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPreco.setText("Preço:");

        jLabelCod.setText("jLabel1");

        jButtonConcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEstoque.setText("Estoque:");

        jNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNome.setText("Nome:");

        txtEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueActionPerformed(evt);
            }
        });

        jUnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUnd.setText("Unidade abnt: ");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("Cadastro de Produto");

        jComboBoxUnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "g", "mL", "L", "pacote", "caixa" }));

        jQtd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jQtd.setText("quantidade:");

        jUnd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUnd1.setText("Habilitar Venda Fracionada:");

        jComboBoxVF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabelTitulo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jQtd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQtdAbnt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jUnd)
                                            .addComponent(jPreco)
                                            .addComponent(jEstoque)
                                            .addComponent(jNome))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxUnd, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jUnd1)
                                        .addGap(26, 26, 26)
                                        .addComponent(jComboBoxVF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConcluir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQtd)
                    .addComponent(txtQtdAbnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUnd)
                    .addComponent(jComboBoxUnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEstoque))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUnd1)
                    .addComponent(jComboBoxVF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCod)
                    .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluir)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        if (opAuxiliar == OpAuxiliar.ocCadastrar || opAuxiliar == OpAuxiliar.ocAlterar) {

            if ("".equals(txtNome.getText()) || "".equals(txtPreco.getText())
                    || "".equals(txtEstoque.getText()) || "".equals(txtQtdAbnt.getText())) {

                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");

            } else {

                produto.setNome(txtNome.getText());
                produto.setQtdUnidadeAbt(Float.parseFloat(txtQtdAbnt.getText()));
                BigDecimal b = new BigDecimal(txtPreco.getText());
                produto.setPreco(b);
                produto.setUnidadeAbnt(jComboBoxUnd.getSelectedItem().toString());
                produto.setQtdEstoque(Float.parseFloat(txtEstoque.getText()));

                try {
                    if (jComboBoxVF.getSelectedItem().toString() == "sim") {
                        produto.setVendaFraconada(true);
                    } else if (jComboBoxVF.getSelectedItem().toString() == "não") {
                        produto.setVendaFraconada(false);
                    }
                    if (opAuxiliar == OpAuxiliar.ocAlterar) {
                        JOptionPane.showMessageDialog(null, "Alteração feita com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");

                    }
                    confirmado = true;
                    dispose();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Habilite ou desabile a venda fracionada!");
                }

            }
        }

        
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        txtNome.setText(null);
        txtPreco.setText(null);
        txtEstoque.setText(null);
        

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInserirAlterarProd dialog = new TelaInserirAlterarProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JLabel jCod;
    private javax.swing.JComboBox<String> jComboBoxUnd;
    private javax.swing.JComboBox<String> jComboBoxVF;
    private javax.swing.JLabel jEstoque;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jPreco;
    private javax.swing.JLabel jQtd;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jUnd;
    private javax.swing.JLabel jUnd1;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtdAbnt;
    // End of variables declaration//GEN-END:variables
}
