/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controladores.ControleProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Funcionario;
import objetos.FuncionarioPF;
import objetos.Produto;
import pdv.OpAuxiliar;

/**
 *
 * @author User
 */
public class TelaProduto extends javax.swing.JDialog {
    private ControleProduto controleProduto;
    private FuncionarioPF usuario;
    
    public TelaProduto(java.awt.Frame parent, boolean modal, FuncionarioPF funcionario) {
        super(parent, modal);
        initComponents();
        usuario = funcionario;
        jTextUsuario.setText(usuario.getNome());
        jTextUsuario.setEditable(false);
        controleProduto = new ControleProduto(new ArrayList<>());
        tabProd.setModel(controleProduto);
        
        for(int i = 0; i > controleProduto.findAll().size(); i++){
            controleProduto.setProduto(i, controleProduto.getProduto(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxBuscarPor = new javax.swing.JComboBox<>();
        jTextPesquisa = new javax.swing.JTextField();
        jButtonBuscarPor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProd = new javax.swing.JTable();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Nome", "Id", "UnidadeAbnt", "Preço", "Estoque", "quantidade unidade", " " }));

        jButtonBuscarPor.setText("----->");
        jButtonBuscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorActionPerformed(evt);
            }
        });

        tabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabProd);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Usuário:");

        jTextUsuario.setText("jTextField1");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jComboBoxBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarPor)))
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );

        setSize(new java.awt.Dimension(870, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaControle telaControle = new TelaControle (null, true, usuario);
        dispose();
        telaControle.setVisible(true);
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Produto produto = new Produto();
        if(TelaInserirAlterarProd.executar(null, OpAuxiliar.ocCadastrar, produto)){
            controleProduto.saveProduto(produto);
            
            }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Confirma confirma = new Confirma(null, true);
        confirma.setVisible(true);
        boolean retorno = confirma.Op();
        if (retorno == true) {
            int i = tabProd.getSelectedRow();
            if (i >= 0) {
                controleProduto.deleteProduto(controleProduto.getProduto(i),i);
                JOptionPane.showMessageDialog(null, "Excluído com sucesso");
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        int i = tabProd.getSelectedRow();
        if(i >= 0){
            Produto produto = controleProduto.getProduto(i);
            if(TelaInserirAlterarProd.executar(null, OpAuxiliar.ocAlterar, produto))
                //controleFuncionario.setCliente(i, cliente);
                controleProduto.updateProduto(produto, i);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorActionPerformed
        String valor = jTextPesquisa.getText();
         
        if ("".equals(valor) && jComboBoxBuscarPor.getSelectedIndex() != 0 ) {
            JOptionPane.showMessageDialog(null, "Digite o item que deseja pesquisar.");
            
        } else {
            switch (jComboBoxBuscarPor.getSelectedIndex()) {
                case 0:
                    controleProduto.findAll();
                    setVisible(false);
                    setVisible(true);
                case 1: //buscar por nome

                    for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 2).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;

                case 2: //buscar por codigo
                   for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 1).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;

                case 3: //buscar por unidadeAbnt
                    for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 3).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;

                case 4: //buscar por preço
                    for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 4).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;

                case 5: //buscar por estoque
                    for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 5).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;
                
                case 6: //buscar por quantidade
                    for (int i = 0; i < controleProduto.ObterPesquisaProduto(valor, 6).size(); i++) {

                        controleProduto.setProduto(i, controleProduto.getProduto(i));
                    }
                    break;

            }
        }
    }//GEN-LAST:event_jButtonBuscarPorActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProduto dialog = new TelaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscarPor;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxBuscarPor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextPesquisa;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JTable tabProd;
    // End of variables declaration//GEN-END:variables
}
