/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controladores.ControleFuncionario;
import enums.Funcao;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Funcionario;
import objetos.FuncionarioPF;
import pdv.OpAuxiliar;
import pdv.ValidarCNP;

/**
 *
 * @author User
 */
public class TelaInserirAlterarFunc extends javax.swing.JDialog {
    private ControleFuncionario controleFuncionario;
    private FuncionarioPF funcionario;
    private OpAuxiliar opAuxiliar;
    private boolean confirmado;
    private boolean isHere = false;
    private int id;
    private ValidarCNP validarCNP;
    
    
    public TelaInserirAlterarFunc(java.awt.Frame parent, OpAuxiliar opAuxiliar, FuncionarioPF funcionario) {
        super(parent, true);
        confirmado = false;
        validarCNP = new ValidarCNP();
        this.opAuxiliar = opAuxiliar;
        this.funcionario = funcionario;
        initComponents();
        controleFuncionario = new ControleFuncionario(new ArrayList<>());
        
        if (opAuxiliar == opAuxiliar.ocAlterar
                || opAuxiliar == OpAuxiliar.ocConsultar) {
            jLabelTitulo.setText(null);
            jLabelTitulo.setText("Alteração de Cadastro");
            jLabelId.setText(Integer.toString(funcionario.getId_func()));
            txtNome.setText(funcionario.getNome());
            txtCpf.setText(funcionario.getCpf());
            txtCpf.setEnabled(false);
            txtTel.setText(funcionario.getTelefone());
            txtSalario.setText(funcionario.getSalario().toPlainString());
            txtSenha.setText(funcionario.getSenha());
            txtSenha2.setText(funcionario.getSenha());
            txtSenha.setVisible(false);
            txtSenha2.setVisible(false);
            jSenha.setVisible(false);
            jSenha1.setVisible(false);
        }else{
            
            id = controleFuncionario.getFuncionario(controleFuncionario.obterListaFuncionarios().size() - 1).getId_func() + 1;
            jLabelId.setText(Integer.toString(id));
        }
    }
    
    public boolean opConfirmada(){
        return confirmado;
    }
    
    public static boolean executar(java.awt.Frame parent, OpAuxiliar opAuxiliar, FuncionarioPF funcionario){
        TelaInserirAlterarFunc telaInserirAlterarFunc = new TelaInserirAlterarFunc(parent, opAuxiliar, funcionario);
        telaInserirAlterarFunc.setLocationRelativeTo(null);
        telaInserirAlterarFunc.setVisible(true);
        return telaInserirAlterarFunc.opConfirmada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jCpf = new javax.swing.JLabel();
        jTextCpf = new javax.swing.JTextField();
        jTextTel = new javax.swing.JTextField();
        jTel = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jNome1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jCpf1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jTel1 = new javax.swing.JLabel();
        jComboBoxFunc = new javax.swing.JComboBox<>();
        jFuncao = new javax.swing.JLabel();
        jSal = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jSenha1 = new javax.swing.JLabel();
        txtSenha2 = new javax.swing.JTextField();
        jSenha2 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonConcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNome.setText("Nome:");

        jCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCpf.setText("CPF:");

        jTextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelActionPerformed(evt);
            }
        });

        jTel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTel.setText("Telefone:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("Novo Funcionário");

        jNome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNome1.setText("Nome/Razão Social:");

        jCpf1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCpf1.setText("CPF/CNPJ:");

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        jTel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTel1.setText("Telefone:");

        jComboBoxFunc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa", "Serviços Gerais", "Estoquista", "Gerente", "Financeiro", " " }));

        jFuncao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFuncao.setText("Função:");

        jSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSal.setText("Salário:");

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        jSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSenha.setText("Senha:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        jSenha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSenha1.setText("Confirmar Senha:");

        txtSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha2ActionPerformed(evt);
            }
        });

        jSenha2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSenha2.setText("ID do Funcionário:");

        jLabelId.setText("jLabel1");

        jButtonConcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabelTitulo)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jSenha2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jSal)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtSalario))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jFuncao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSenha1)
                                    .addComponent(jSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(txtSenha2))))))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConcluir)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCpf1)
                                    .addComponent(jTel1))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(txtTel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFuncao)
                    .addComponent(jComboBoxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSal)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCpf1)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSenha1)
                    .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSenha2)
                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluir)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha2ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        txtNome.setText(null);
        txtCpf.setText(null);
        txtTel.setText(null);
        txtSalario.setText(null);
        txtSenha.setText(null);
        txtSenha2.setText(null);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        if (opAuxiliar == OpAuxiliar.ocCadastrar || opAuxiliar == OpAuxiliar.ocAlterar) {
            
            boolean isCpf = validarCNP.isCPF(txtCpf.getText());
            System.out.println(isCpf);
            for (int i = 0; i < controleFuncionario.obterListaFuncionarios().size(); i++) {
                if (controleFuncionario.getFuncionario(i).getCpf().equals(txtCpf.getText())) {
                    isCpf = false;
                    isHere = true;
                }
            }
            
            if (isCpf == false && opAuxiliar != OpAuxiliar.ocAlterar ) {
                   if(isHere == false){
                     JOptionPane.showMessageDialog(null, "CPF inválido!");
                   }else{
                     JOptionPane.showMessageDialog(null, "CPF Já cadastrado!");  
                   }
            
            }else if("".equals(txtNome.getText()) || "".equals(txtSalario.getText()) || "".equals(txtSenha2.getText())
                    || "".equals(txtSenha.getText()) || "".equals(txtTel.getText())){
            
                JOptionPane.showMessageDialog(null, "Os campos marcados com asterístico devem ser preenchidos.");
            
            }else{
                if(!txtSenha.getText().equals(txtSenha2.getText())){
                    JOptionPane.showMessageDialog(null, "A confirmação de senha deve ser igual a senha desejada!");
                }else{
                    funcionario.setNome(txtNome.getText());
                    funcionario.setCpf(txtCpf.getText());
                    funcionario.setTelefone(txtTel.getText());
                    funcionario.setFuncao(jComboBoxFunc.getSelectedItem().toString());
                    BigDecimal b = new BigDecimal(txtSalario.getText());
                    funcionario.setSalario(b);
                    funcionario.setSenha(txtSenha.getText());
                    funcionario.setId_func(Integer.parseInt(jLabelId.getText()));
                    
                    if(opAuxiliar == OpAuxiliar.ocAlterar){
                        JOptionPane.showMessageDialog(null, "Alteração feita com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                        
                    }
                        confirmado = true;
                        dispose();
                }
            }
            
            
            
            
            
            
            
            
        }
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInserirAlterarFunc dialog = new TelaInserirAlterarFunc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JComboBox<String> jComboBoxFunc;
    private javax.swing.JLabel jCpf;
    private javax.swing.JLabel jCpf1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jFuncao;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNome1;
    private javax.swing.JLabel jSal;
    private javax.swing.JLabel jSenha;
    private javax.swing.JLabel jSenha1;
    private javax.swing.JLabel jSenha2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jTel;
    private javax.swing.JLabel jTel1;
    private javax.swing.JTextField jTextCpf;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextTel;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenha2;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
